#!/bin/bash

function snakeCamel() {
    cat - | sed -E 's/_([a-z])/\U\1/g'
}

function camelSnake() {
    cat - | sed -E 's/([a-z])([A-Z])/\1_\L\2/g; s/^(.)/\L\1/; s/([\t ])(.)/\1\L\2/;'
}

while read line; do
  if [[ $line =~ _ ]]; then
    echo $line | snakeCamel
  else
    echo $line | camelSnake
  fi
done
